### PR TITLE
commented out unused variable initialization

### PR DESCRIPTION
**Pull request by Redar13**
bro

### CODE REVIEW

**Comment by Redar13** [comment]
Your commit which had an array optimization was leaking memory due to an unused newly introduced variable which was never removed from memory. Please accept this.

**Comment by NeeEoo** [comment]
I didnt introduce it it was already there

https://github.com/HaxeFoundation/hxcpp/blob/master/src/Array.cpp#L111

plus it gets optimized away at compile time

**Comment by Redar13** [comment]
Well, in such a case I have optimizer does not work, because when I downloaded this fork I had this problem, but after fixing it fixed.🤷‍♂️
Also this field is very weird.

**Comment by NeeEoo** [comment]
> Well, in such a case I have optimizer does not work, because when I downloaded this fork I had this problem, but after fixing it fixed.🤷‍♂️
> 
> Also this field is very weird.

Either way it's been in here since forever. Before my commit. Plus this is literally unallocated instantly it does nothing, prove it, decompile a release build it wont be there

**Pull request merged**
